/**:
  ros__parameters:
    plugin_denylist:
      # common
      - safety_area
      # extras
      - image_pub
      - vibration
      #- distance_sensor
      #- rangefinder
      - wheel_odometry
   # plugin_whitelist: []


    # plugin_allowlist:
    #   - 'sys_*'